name: Build Then Release
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v1.44
      - uses: actions/checkout@v4
      - name: Build
        run: deno task build
      - name: Publish package
        run: deno publish