name: Build Then Release
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.5"
          
      - name: use deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.2.8

      - uses: actions/checkout@v4

      - name: Build
        run: deno task build

      - name: Publish package
        run: npx jsr publish --allow-slow-types
